/* Copyright (c) 2017-2019 ARM Limited
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/***********************************************************************************************************************
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 * THIS FILE IS AN AUTO-GENERATED FILE - DO NOT MODIFY IT.
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 * Template Version 1.0
 * Generated by tools/spm/generate_partition_code.py Version 1.0
 **********************************************************************************************************************/

#ifndef PSA_ACTUATOR_CONTROL_SRV_PARTITION_H
#define PSA_ACTUATOR_CONTROL_SRV_PARTITION_H

#define ACTUATOR_CONTROL_SRV_ID 65544

#define ACTUATOR_CONTROL_SRV_ROT_SRV_COUNT (1UL)
#define ACTUATOR_CONTROL_SRV_EXT_ROT_SRV_COUNT (0UL)

/* ACTUATOR_CONTROL_SRV event flags */
#define ACTUATOR_CONTROL_SRV_RESERVED1_POS (1UL)
#define ACTUATOR_CONTROL_SRV_RESERVED1_MSK (1UL << ACTUATOR_CONTROL_SRV_RESERVED1_POS)

#define ACTUATOR_CONTROL_SRV_RESERVED2_POS (2UL)
#define ACTUATOR_CONTROL_SRV_RESERVED2_MSK (1UL << ACTUATOR_CONTROL_SRV_RESERVED2_POS)


#define ACTUATOR_CONTROL_SRV_WAIT_ANY_IRQ_MSK (0)

#define ACTUATOR_CONTROL_PROCESS_PACKET_MSK_POS (4UL)
#define ACTUATOR_CONTROL_PROCESS_PACKET_MSK (1UL << ACTUATOR_CONTROL_PROCESS_PACKET_MSK_POS)

#define ACTUATOR_CONTROL_SRV_WAIT_ANY_SID_MSK (\
    ACTUATOR_CONTROL_PROCESS_PACKET_MSK)


#endif // PSA_ACTUATOR_CONTROL_SRV_PARTITION_H
